name: Docker CI/CD Workflow
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /volume1/vscode/app/githubActionTest
            git pull

      - name : Build Docker Image
        run : docker build -t ${{ secrets.DOCKER_USERNAME }}/my-application:latest .
      
      - name: Push Docker Image
        run : docker push ${{ secrets.DOCKER_USERNAME }}/my-application:latest

      - name: Stop Docker
        run : docker stop test || true    

      - name: Rm Docker
        run : docker rm test || true  

      - name: run Docker
        run : docker run -d --name test -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/my-application:latest
            
